#!/usr/bin/env python3
"""Write .env from .env.example with freshly generated secrets.

Run once, before the first `docker compose up`: the database keeps the
passwords it was created with, so rotating them later needs manual steps.
Standard library only.
"""

import base64
import hashlib
import hmac
import json
import secrets
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EXAMPLE = ROOT / ".env.example"
TARGET = ROOT / ".env"


def b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode()


def supabase_key(role: str, jwt_secret: str) -> str:
    """HS256 API key, as Supabase's own key generator mints it."""
    now = int(time.time())
    header = b64url(json.dumps({"alg": "HS256", "typ": "JWT"}).encode())
    claims = {"role": role, "iss": "supabase", "iat": now, "exp": now + 10 * 365 * 24 * 3600}
    payload = b64url(json.dumps(claims).encode())
    signing_input = f"{header}.{payload}"
    signature = hmac.new(jwt_secret.encode(), signing_input.encode(), hashlib.sha256).digest()
    return f"{signing_input}.{b64url(signature)}"


# NIST P-256 curve parameters.
_P = 0xFFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFF
_N = 0xFFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551
_A = _P - 3
_G = (
    0x6B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C296,
    0x4FE342E2FE1A7F9B8EE7EB4A7C0F9E162BCE33576B315ECECBB6406837BF51F5,
)


def _ec_add(p: tuple[int, int] | None, q: tuple[int, int] | None) -> tuple[int, int] | None:
    if p is None:
        return q
    if q is None:
        return p
    if p[0] == q[0] and (p[1] + q[1]) % _P == 0:
        return None
    if p == q:
        slope = (3 * p[0] * p[0] + _A) * pow(2 * p[1], -1, _P)
    else:
        slope = (q[1] - p[1]) * pow(q[0] - p[0], -1, _P)
    x = (slope * slope - p[0] - q[0]) % _P
    return x, (slope * (p[0] - x) - p[1]) % _P


def signing_jwks(jwt_secret: str) -> str:
    """Auth's JWT_KEYS: a fresh ES256 signing key plus the HS256 secret for verifying."""
    d = secrets.randbelow(_N - 1) + 1
    point, addend, k = None, _G, d
    while k:
        if k & 1:
            point = _ec_add(point, addend)
        addend = _ec_add(addend, addend)
        k >>= 1
    assert point is not None

    def coord(n: int) -> str:
        return b64url(n.to_bytes(32, "big"))

    ec = {"kty": "EC", "crv": "P-256", "alg": "ES256", "use": "sig", "key_ops": ["sign", "verify"]}
    ec |= {"kid": secrets.token_hex(8), "x": coord(point[0]), "y": coord(point[1]), "d": coord(d)}
    oct_key = {"kty": "oct", "alg": "HS256", "use": "sig", "key_ops": ["verify"]}
    oct_key |= {"kid": secrets.token_hex(8), "k": b64url(jwt_secret.encode())}
    return json.dumps([ec, oct_key], separators=(",", ":"))


def main() -> None:
    if TARGET.exists():
        sys.exit(f"{TARGET} already exists; delete it first if you really want new secrets.")
    jwt_secret = secrets.token_hex(32)
    values = {
        "POSTGRES_PASSWORD": secrets.token_hex(24),
        "API_SERVICE_DB_PASSWORD": secrets.token_hex(24),
        "JWT_SECRET": jwt_secret,
        "ANON_KEY": supabase_key("anon", jwt_secret),
        "SERVICE_ROLE_KEY": supabase_key("service_role", jwt_secret),
        "JWT_KEYS": f"'{signing_jwks(jwt_secret)}'",
        "DASHBOARD_PASSWORD": secrets.token_hex(16),
        "PG_META_CRYPTO_KEY": secrets.token_hex(32),
        "S3_PROTOCOL_ACCESS_KEY_ID": secrets.token_hex(16),
        "S3_PROTOCOL_ACCESS_KEY_SECRET": secrets.token_hex(32),
        "ADMIN_PASSWORD": secrets.token_urlsafe(12),
    }
    lines = []
    for line in EXAMPLE.read_text().splitlines():
        key = line.split("=", 1)[0]
        if key in values:
            line = f"{key}={values[key]}"
        elif line.startswith("# Secrets."):
            line = "# Secrets, generated by infra/gen_secrets.py."
        lines.append(line)
    TARGET.write_text("\n".join(lines) + "\n")
    TARGET.chmod(0o600)
    print(f"Wrote {TARGET}. Admin password: {values['ADMIN_PASSWORD']}")


if __name__ == "__main__":
    main()
