"""Prompts for the SMS walker; English fills any missing key.

``STOP`` / ``RESTART`` stay English in every locale (``flow.py`` only also
matches AR keywords), so the copy keeps them verbatim. Closed-set values stay
canonical English on the wire; only display copy is localized.
"""

from __future__ import annotations

from api.channels.languages import resolve_strings

_STRINGS: dict[str, dict[str, str]] = {
    "intro": {
        "en": "Welcome to the RASID damage reporting service. Reply STOP to cancel, RESTART to start over.",
        "ar": "مرحبًا بك في خدمة الإبلاغ عن الأضرار RASID. أرسل STOP للإلغاء أو RESTART للبدء من جديد.",
        "es": "Bienvenido al servicio de reporte de daños RASID. Responda STOP para cancelar o RESTART para empezar de nuevo.",
        "fr": "Bienvenue au service de signalement de dommages RASID. Répondez STOP pour annuler ou RESTART pour recommencer.",
        "ru": "Добро пожаловать в службу сообщений о повреждениях RASID. Отправьте STOP для отмены или RESTART, чтобы начать заново.",
        "zh": "欢迎使用 RASID 损害报告服务。回复 STOP 取消，回复 RESTART 重新开始。",
    },
    "consent_notice": {
        "en": "By continuing you agree to our privacy policy: {privacy_url}",
        "ar": "بالمتابعة، أنت توافق على سياسة الخصوصية الخاصة بنا: {privacy_url}",
        "es": "Al continuar, acepta nuestra política de privacidad: {privacy_url}",
        "fr": "En continuant, vous acceptez notre politique de confidentialité : {privacy_url}",
        "ru": "Продолжая, вы соглашаетесь с нашей политикой конфиденциальности: {privacy_url}",
        "zh": "继续即表示您同意我们的隐私政策：{privacy_url}",
    },
    "ask_language": {
        "en": "Choose a language:",
        "ar": "اختر لغة:",
        "es": "Elija un idioma:",
        "fr": "Choisissez une langue :",
        "ru": "Выберите язык:",
        "zh": "请选择语言：",
    },
    "lang_reply_hint": {
        "en": "Reply with a number.",
        "ar": "أرسل رقمًا.",
        "es": "Responda con un número.",
        "fr": "Répondez avec un numéro.",
        "ru": "Ответьте номером.",
        "zh": "请回复数字。",
    },
    "ask_crisis": {
        "en": "Which event are you reporting? Reply with the number.",
        "ar": "ما هو الحدث الذي تبلغ عنه؟ أرسل الرقم.",
        "es": "¿Qué evento está reportando? Responda con el número.",
        "fr": "Quel événement signalez-vous ? Répondez avec le numéro.",
        "ru": "О каком событии вы сообщаете? Ответьте номером.",
        "zh": "您要报告哪个事件？请回复编号。",
    },
    "no_active_crises": {
        "en": "There are no active events to report against right now. Please try again later.",
        "ar": "لا توجد أحداث نشطة للإبلاغ عنها حاليًا. يرجى المحاولة لاحقًا.",
        "es": "No hay eventos activos para reportar en este momento. Inténtelo de nuevo más tarde.",
        "fr": "Aucun événement actif à signaler pour le moment. Veuillez réessayer plus tard.",
        "ru": "Сейчас нет активных событий для сообщения. Пожалуйста, попробуйте позже.",
        "zh": "目前没有可报告的活动事件。请稍后再试。",
    },
    "ask_damage": {
        "en": "How badly is the building damaged?\n1. Minimal\n2. Partial\n3. Complete\n\nReply with a number.",
        "ar": "ما مدى الضرر الذي لحق بالمبنى؟\n1. طفيف\n2. جزئي\n3. كامل\n\nأرسل رقمًا.",
        "es": "¿Qué tan dañado está el edificio?\n1. Mínimo\n2. Parcial\n3. Total\n\nResponda con un número.",
        "fr": "Quel est le niveau de dégâts du bâtiment ?\n1. Minime\n2. Partiel\n3. Total\n\nRépondez avec un numéro.",
        "ru": "Насколько повреждено здание?\n1. Незначительно\n2. Частично\n3. Полностью\n\nОтветьте номером.",
        "zh": "建筑物的损坏程度如何？\n1. 轻微\n2. 部分\n3. 完全\n\n请回复数字。",
    },
    "ask_description": {
        "en": "Describe the damage and the building in a few words (this replaces a photo, so please be specific).",
        "ar": "صف الضرر والمبنى بكلمات قليلة (هذا يحل محل الصورة، لذا يرجى التحديد).",
        "es": "Describa el daño y el edificio en pocas palabras (esto reemplaza una foto, así que sea específico).",
        "fr": "Décrivez les dégâts et le bâtiment en quelques mots (cela remplace une photo, soyez donc précis).",
        "ru": "Опишите повреждения и здание в нескольких словах (это заменяет фотографию, поэтому будьте конкретны).",
        "zh": "请用几句话描述损害和建筑物（这将代替照片，请尽量具体）。",
    },
    "ask_route": {
        "en": "How can responders find the building? Give the address or directions (street, district, landmarks).",
        "ar": "كيف يمكن لفرق الاستجابة العثور على المبنى؟ اذكر العنوان أو الاتجاهات (الشارع، الحي، المعالم).",
        "es": "¿Cómo pueden los equipos de respuesta encontrar el edificio? Indique la dirección o cómo llegar (calle, distrito, puntos de referencia).",
        "fr": "Comment les secours peuvent-ils trouver le bâtiment ? Indiquez l'adresse ou l'itinéraire (rue, quartier, points de repère).",
        "ru": "Как спасатели могут найти здание? Укажите адрес или ориентиры (улица, район, ориентиры).",
        "zh": "救援人员如何找到这座建筑？请提供地址或路线（街道、区域、地标）。",
    },
    "ask_debris": {
        "en": "Is there debris blocking access?\n1. Yes\n2. No\n3. Not sure\n\nReply with a number.",
        "ar": "هل توجد أنقاض تعيق الوصول؟\n1. نعم\n2. لا\n3. غير متأكد\n\nأرسل رقمًا.",
        "es": "¿Hay escombros que bloquean el acceso?\n1. Sí\n2. No\n3. No estoy seguro\n\nResponda con un número.",
        "fr": "Des débris bloquent-ils l'accès ?\n1. Oui\n2. Non\n3. Pas sûr\n\nRépondez avec un numéro.",
        "ru": "Есть ли обломки, блокирующие доступ?\n1. Да\n2. Нет\n3. Не уверен\n\nОтветьте номером.",
        "zh": "是否有碎片阻挡通道？\n1. 是\n2. 否\n3. 不确定\n\n请回复数字。",
    },
    "ask_infra": {
        "en": "What type of structure is it? Reply with the number.",
        "ar": "ما نوع المبنى؟ أرسل الرقم.",
        "es": "¿Qué tipo de estructura es? Responda con el número.",
        "fr": "De quel type de structure s'agit-il ? Répondez avec le numéro.",
        "ru": "Какой это тип сооружения? Ответьте номером.",
        "zh": "这是什么类型的建筑？请回复编号。",
    },
    "prompt_infra_other": {
        "en": "Please describe the structure type in a few words.",
        "ar": "يرجى وصف نوع المبنى بكلمات قليلة.",
        "es": "Describa el tipo de estructura en pocas palabras.",
        "fr": "Décrivez le type de structure en quelques mots.",
        "ru": "Опишите тип сооружения в нескольких словах.",
        "zh": "请用几句话描述建筑类型。",
    },
    "ask_nature": {
        "en": "What caused the damage? Reply with the number.",
        "ar": "ما سبب الضرر؟ أرسل الرقم.",
        "es": "¿Qué causó el daño? Responda con el número.",
        "fr": "Qu'est-ce qui a causé les dégâts ? Répondez avec le numéro.",
        "ru": "Что вызвало повреждение? Ответьте номером.",
        "zh": "是什么造成了损害？请回复编号。",
    },
    "nature_other": {
        "en": "Other",
        "ar": "أخرى",
        "es": "Otro",
        "fr": "Autre",
        "ru": "Другое",
        "zh": "其他",
    },
    "prompt_nature_other": {
        "en": "Please describe what caused the damage.",
        "ar": "يرجى وصف سبب الضرر.",
        "es": "Describa qué causó el daño.",
        "fr": "Décrivez ce qui a causé les dégâts.",
        "ru": "Опишите, что вызвало повреждение.",
        "zh": "请描述造成损害的原因。",
    },
    "review_header": {
        "en": "Please review your report:",
        "ar": "يرجى مراجعة بلاغك:",
        "es": "Revise su reporte:",
        "fr": "Veuillez vérifier votre signalement :",
        "ru": "Пожалуйста, проверьте ваше сообщение:",
        "zh": "请检查您的报告：",
    },
    "review_question": {
        "en": "Reply 1 to SUBMIT, 2 to EDIT, 3 to CANCEL.",
        "ar": "أرسل 1 للإرسال، 2 للتعديل، 3 للإلغاء.",
        "es": "Responda 1 para ENVIAR, 2 para EDITAR, 3 para CANCELAR.",
        "fr": "Répondez 1 pour ENVOYER, 2 pour MODIFIER, 3 pour ANNULER.",
        "ru": "Ответьте 1 — ОТПРАВИТЬ, 2 — ИЗМЕНИТЬ, 3 — ОТМЕНИТЬ.",
        "zh": "回复 1 提交，2 编辑，3 取消。",
    },
    "label_crisis": {
        "en": "Event",
        "ar": "الحدث",
        "es": "Evento",
        "fr": "Événement",
        "ru": "Событие",
        "zh": "事件",
    },
    "label_damage": {
        "en": "Damage",
        "ar": "الضرر",
        "es": "Daño",
        "fr": "Dégâts",
        "ru": "Повреждение",
        "zh": "损害",
    },
    "label_description": {
        "en": "Description",
        "ar": "الوصف",
        "es": "Descripción",
        "fr": "Description",
        "ru": "Описание",
        "zh": "描述",
    },
    "label_route": {
        "en": "Location",
        "ar": "الموقع",
        "es": "Ubicación",
        "fr": "Emplacement",
        "ru": "Местоположение",
        "zh": "位置",
    },
    "label_debris": {
        "en": "Debris",
        "ar": "الأنقاض",
        "es": "Escombros",
        "fr": "Débris",
        "ru": "Обломки",
        "zh": "碎片",
    },
    "label_infra": {
        "en": "Structure",
        "ar": "المبنى",
        "es": "Estructura",
        "fr": "Structure",
        "ru": "Сооружение",
        "zh": "建筑",
    },
    "label_nature": {
        "en": "Cause",
        "ar": "السبب",
        "es": "Causa",
        "fr": "Cause",
        "ru": "Причина",
        "zh": "原因",
    },
    "ask_edit": {
        "en": "What would you like to change? Reply with the number.",
        "ar": "ما الذي تريد تغييره؟ أرسل الرقم.",
        "es": "¿Qué desea cambiar? Responda con el número.",
        "fr": "Que souhaitez-vous modifier ? Répondez avec le numéro.",
        "ru": "Что вы хотите изменить? Ответьте номером.",
        "zh": "您想修改什么？请回复编号。",
    },
    "generic_pick_number": {
        "en": "Reply with the number of your choice.",
        "ar": "أرسل رقم اختيارك.",
        "es": "Responda con el número de su elección.",
        "fr": "Répondez avec le numéro de votre choix.",
        "ru": "Ответьте номером вашего выбора.",
        "zh": "请回复您选择的编号。",
    },
    "generic_pick_numbers": {
        "en": "Reply with the numbers, separated by commas (e.g. 1,3).",
        "ar": "أرسل الأرقام مفصولة بفواصل (مثال: 1,3).",
        "es": "Responda con los números separados por comas (ej. 1,3).",
        "fr": "Répondez avec les numéros séparés par des virgules (ex. 1,3).",
        "ru": "Ответьте номерами через запятую (например, 1,3).",
        "zh": "请回复编号，用逗号分隔（例如 1,3）。",
    },
    "generic_free_hint": {
        "en": "Reply with your answer.",
        "ar": "أرسل إجابتك.",
        "es": "Responda con su respuesta.",
        "fr": "Répondez avec votre réponse.",
        "ru": "Напишите ваш ответ.",
        "zh": "请回复您的答案。",
    },
    "generic_skip_hint": {
        "en": "Reply 0 to skip.",
        "ar": "أرسل 0 للتخطي.",
        "es": "Responda 0 para omitir.",
        "fr": "Répondez 0 pour ignorer.",
        "ru": "Ответьте 0, чтобы пропустить.",
        "zh": "回复 0 跳过。",
    },
    "generic_max": {
        "en": "Pick at most {n}.",
        "ar": "اختر {n} كحد أقصى.",
        "es": "Elija como máximo {n}.",
        "fr": "Choisissez au maximum {n}.",
        "ru": "Выберите не более {n}.",
        "zh": "最多选择 {n} 个。",
    },
    "at_least_one": {
        "en": "Please pick at least one option.",
        "ar": "يرجى اختيار خيار واحد على الأقل.",
        "es": "Elija al menos una opción.",
        "fr": "Veuillez choisir au moins une option.",
        "ru": "Пожалуйста, выберите хотя бы один вариант.",
        "zh": "请至少选择一个选项。",
    },
    "invalid_choice": {
        "en": "Sorry, I didn't understand. Please reply with a valid number.",
        "ar": "عذرًا، لم أفهم. يرجى الرد برقم صحيح.",
        "es": "Lo siento, no entendí. Responda con un número válido.",
        "fr": "Désolé, je n'ai pas compris. Veuillez répondre avec un numéro valide.",
        "ru": "Извините, не понял. Пожалуйста, ответьте корректным номером.",
        "zh": "抱歉，我没有理解。请回复有效的数字。",
    },
    "submitted": {
        "en": "Thank you. Your report has been submitted. Reference: {ref}",
        "ar": "شكرًا لك. تم إرسال بلاغك. الرقم المرجعي: {ref}",
        "es": "Gracias. Su reporte ha sido enviado. Referencia: {ref}",
        "fr": "Merci. Votre signalement a été envoyé. Référence : {ref}",
        "ru": "Спасибо. Ваше сообщение отправлено. Номер: {ref}",
        "zh": "谢谢。您的报告已提交。参考号：{ref}",
    },
    "submit_failed": {
        "en": "Sorry, something went wrong submitting your report. Please try again shortly.",
        "ar": "عذرًا، حدث خطأ أثناء إرسال بلاغك. يرجى المحاولة مرة أخرى قريبًا.",
        "es": "Lo siento, ocurrió un error al enviar su reporte. Inténtelo de nuevo en breve.",
        "fr": "Désolé, une erreur s'est produite lors de l'envoi de votre signalement. Veuillez réessayer sous peu.",
        "ru": "Извините, при отправке сообщения произошла ошибка. Пожалуйста, попробуйте снова чуть позже.",
        "zh": "抱歉，提交报告时出错。请稍后重试。",
    },
    "cancelled": {
        "en": "Your report has been cancelled. Text us again any time to start over.",
        "ar": "تم إلغاء بلاغك. راسلنا في أي وقت للبدء من جديد.",
        "es": "Su reporte ha sido cancelado. Envíenos un mensaje cuando quiera para empezar de nuevo.",
        "fr": "Votre signalement a été annulé. Envoyez-nous un message à tout moment pour recommencer.",
        "ru": "Ваше сообщение отменено. Напишите нам в любое время, чтобы начать заново.",
        "zh": "您的报告已取消。随时可以再次发送短信重新开始。",
    },
    "damage_minimal": {
        "en": "Minimal",
        "ar": "طفيف",
        "es": "Mínimo",
        "fr": "Minime",
        "ru": "Незначительный",
        "zh": "轻微",
    },
    "damage_partial": {
        "en": "Partial",
        "ar": "جزئي",
        "es": "Parcial",
        "fr": "Partiel",
        "ru": "Частичный",
        "zh": "部分",
    },
    "damage_complete": {
        "en": "Complete",
        "ar": "كامل",
        "es": "Total",
        "fr": "Total",
        "ru": "Полный",
        "zh": "完全",
    },
    "debris_yes": {
        "en": "Yes",
        "ar": "نعم",
        "es": "Sí",
        "fr": "Oui",
        "ru": "Да",
        "zh": "是",
    },
    "debris_no": {
        "en": "No",
        "ar": "لا",
        "es": "No",
        "fr": "Non",
        "ru": "Нет",
        "zh": "否",
    },
    "debris_unknown": {
        "en": "Not sure",
        "ar": "غير متأكد",
        "es": "No estoy seguro",
        "fr": "Pas sûr",
        "ru": "Не уверен",
        "zh": "不确定",
    },
    "infra_residential": {
        "en": "Residential",
        "ar": "سكني",
        "es": "Residencial",
        "fr": "Résidentiel",
        "ru": "Жилое",
        "zh": "住宅",
    },
    "infra_commercial": {
        "en": "Commercial",
        "ar": "تجاري",
        "es": "Comercial",
        "fr": "Commercial",
        "ru": "Коммерческое",
        "zh": "商业",
    },
    "infra_government": {
        "en": "Government",
        "ar": "حكومي",
        "es": "Gubernamental",
        "fr": "Gouvernemental",
        "ru": "Государственное",
        "zh": "政府",
    },
    "infra_utility": {
        "en": "Utility",
        "ar": "مرافق",
        "es": "Servicios públicos",
        "fr": "Service public",
        "ru": "Коммунальное",
        "zh": "公用事业",
    },
    "infra_transport": {
        "en": "Transport",
        "ar": "نقل",
        "es": "Transporte",
        "fr": "Transport",
        "ru": "Транспорт",
        "zh": "交通",
    },
    "infra_community": {
        "en": "Community",
        "ar": "مجتمعي",
        "es": "Comunitario",
        "fr": "Communautaire",
        "ru": "Общественное",
        "zh": "社区",
    },
    "infra_public_spaces": {
        "en": "Public space",
        "ar": "مساحة عامة",
        "es": "Espacio público",
        "fr": "Espace public",
        "ru": "Общественное пространство",
        "zh": "公共空间",
    },
    "infra_other": {
        "en": "Other",
        "ar": "أخرى",
        "es": "Otro",
        "fr": "Autre",
        "ru": "Другое",
        "zh": "其他",
    },
}


def strings(lang: str) -> dict[str, str]:
    return resolve_strings(_STRINGS, lang)
