"""Crisis analysis-report PDFs (generated by an Arq job) and live analysis metrics.

The path segment is analysis_reports because /crises/{id}/reports already
serves citizen damage reports.
"""

from __future__ import annotations

import uuid
from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, Request
from sqlalchemy import text

from api.admin.guards import require_crisis
from api.analysis.builder import build_report_metrics
from api.auth.dependency import require_coordinator
from api.auth.models import Coordinator
from api.core.app_state import AppState, get_app_state, get_storage
from api.core.arq import ArqEnqueuer, JobEnqueuer
from api.core.rate_limit import limit
from api.core.storage import ReportPdfStore, StorageClient
from api.schemas.analysis_metrics import AnalysisMetricsResponse
from api.schemas.crisis_reports import (
    CrisisReportCreatedResponse,
    CrisisReportDetail,
    CrisisReportListItem,
)

router = APIRouter()

# Short-lived: the PDF is opened right after the detail call resolves.
_DOWNLOAD_URL_TTL_SECONDS = 15 * 60


def get_report_generation_enqueuer(
    state: Annotated[AppState, Depends(get_app_state)],
) -> JobEnqueuer:
    return ArqEnqueuer(state.arq_pool, "generate_crisis_report")


def get_report_pdf_store(
    storage: Annotated[StorageClient, Depends(get_storage)],
) -> ReportPdfStore:
    return storage


@router.post(
    "/crises/{crisis_id}/analysis_reports",
    response_model=CrisisReportCreatedResponse,
    status_code=201,
)
@limit("30/minute")
async def create_crisis_report(
    request: Request,
    crisis_id: uuid.UUID,
    coordinator: Annotated[Coordinator, Depends(require_coordinator)],
    enqueuer: Annotated[JobEnqueuer, Depends(get_report_generation_enqueuer)],
    state: Annotated[AppState, Depends(get_app_state)],
) -> CrisisReportCreatedResponse:
    """Insert and enqueue in one transaction, so a failed enqueue leaves no running row."""
    async with state.sessionmaker() as session, session.begin():
        await require_crisis(session, crisis_id)

        row = (
            await session.execute(
                text(
                    "insert into public.crisis_reports "
                    "    (crisis_id, created_by, created_by_email, status) "
                    "values (:crisis_id, :created_by, :created_by_email, 'running') "
                    "returning id, status, created_at"
                ),
                {
                    "crisis_id": str(crisis_id),
                    "created_by": str(coordinator.id),
                    # The runtime role cannot read auth.users, so snapshot the email.
                    "created_by_email": coordinator.email,
                },
            )
        ).one()
        await enqueuer.enqueue(row.id)

    return CrisisReportCreatedResponse(id=row.id, status=row.status, created_at=row.created_at)


@router.get(
    "/crises/{crisis_id}/analysis_reports",
    response_model=list[CrisisReportListItem],
)
async def list_crisis_reports(
    crisis_id: uuid.UUID,
    state: Annotated[AppState, Depends(get_app_state)],
) -> list[CrisisReportListItem]:
    async with state.sessionmaker() as session:
        rows = (
            await session.execute(
                text(
                    "select id, created_at, created_by, created_by_email, status, phase, "
                    "       report_count, coverage_pct, storage_key "
                    "from public.crisis_reports "
                    "where crisis_id = :id "
                    "order by created_at desc"
                ),
                {"id": str(crisis_id)},
            )
        ).all()

    return [
        CrisisReportListItem(
            id=r.id,
            created_at=r.created_at,
            created_by=r.created_by,
            created_by_email=r.created_by_email,
            status=r.status,
            phase=r.phase,
            report_count=r.report_count,
            coverage_pct=float(r.coverage_pct) if r.coverage_pct is not None else None,
            download_ready=r.status == "succeeded" and r.storage_key is not None,
        )
        for r in rows
    ]


@router.get(
    "/crises/{crisis_id}/analysis_reports/{report_id}",
    response_model=CrisisReportDetail,
)
async def get_crisis_report(
    crisis_id: uuid.UUID,
    report_id: uuid.UUID,
    store: Annotated[ReportPdfStore, Depends(get_report_pdf_store)],
    state: Annotated[AppState, Depends(get_app_state)],
) -> CrisisReportDetail:
    async with state.sessionmaker() as session:
        row = (
            await session.execute(
                text(
                    "select id, crisis_id, created_at, created_by, created_by_email, "
                    "       status, phase, progress_count, progress_total, error, "
                    "       ended_at, storage_key, report_count, device_count, "
                    "       building_count, coverage_pct "
                    "from public.crisis_reports "
                    "where id = :id and crisis_id = :crisis_id"
                ),
                {"id": str(report_id), "crisis_id": str(crisis_id)},
            )
        ).first()
    if row is None:
        raise HTTPException(status_code=404, detail="report not found")

    download_url: str | None = None
    if row.status == "succeeded" and row.storage_key is not None:
        download_url = await store.sign_report_url(row.storage_key, _DOWNLOAD_URL_TTL_SECONDS)

    return CrisisReportDetail(
        id=row.id,
        crisis_id=row.crisis_id,
        created_at=row.created_at,
        created_by=row.created_by,
        created_by_email=row.created_by_email,
        status=row.status,
        phase=row.phase,
        progress_count=row.progress_count,
        progress_total=row.progress_total,
        error=row.error,
        ended_at=row.ended_at,
        report_count=row.report_count,
        device_count=row.device_count,
        building_count=row.building_count,
        coverage_pct=float(row.coverage_pct) if row.coverage_pct is not None else None,
        download_url=download_url,
    )


@router.get(
    "/crises/{crisis_id}/analysis_metrics",
    response_model=AnalysisMetricsResponse,
)
@limit("30/minute")
async def get_crisis_analysis_metrics(
    request: Request,
    crisis_id: uuid.UUID,
    state: Annotated[AppState, Depends(get_app_state)],
) -> AnalysisMetricsResponse:
    """Deterministic report metrics computed live, without the LLM narrative or PDF."""
    async with state.sessionmaker() as session:
        await require_crisis(session, crisis_id)

        metrics = await build_report_metrics(session, crisis_id)

    return AnalysisMetricsResponse.from_metrics(metrics)
